addSbtPlugin("org.scalameta"     % "sbt-scalafmt"         % "2.4.2")
addSbtPlugin("com.eed3si9n"      % "sbt-assembly"         % "1.0.0")
addSbtPlugin("org.foundweekends" % "sbt-bintray"          % "0.6.1")
addSbtPlugin("com.github.gseitz" % "sbt-protobuf"         % "0.6.5")
addSbtPlugin("io.shiftleft"      % "sbt-ci-release-early" % "2.0.16")
