addSbtPlugin("org.scalameta"             % "sbt-scalafmt"         % "2.4.2")
addSbtPlugin("com.eed3si9n"              % "sbt-assembly"         % "0.15.0")
addSbtPlugin("org.foundweekends"         % "sbt-bintray"          % "0.5.6")
addSbtPlugin("com.github.gseitz"         % "sbt-protobuf"         % "0.6.5")
addSbtPlugin("io.shiftleft"              % "sbt-ci-release-early" % "1.2.4")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"         % "0.1.14")
